
INSERT INTO OPZR.OFFERING_PORTFOLIO(OFFERING_PORTFOLIO_NAME) VALUES ("Core Business Operations");

INSERT INTO OPZR.OFFERING(OFFERING_PORTFOLIO_ID, OFFERING_NAME) VALUES (1,"Core Technology Operations");
INSERT INTO OPZR.OFFERING(OFFERING_PORTFOLIO_ID, OFFERING_NAME) VALUES (1,"Cloud Engineering");
INSERT INTO OPZR.OFFERING(OFFERING_PORTFOLIO_ID, OFFERING_NAME) VALUES (1,"Application Mordernization and Innovation");

INSERT INTO OPZR.ACCOUNT(OFFERING_ID, ACCOUNT_NAME) VALUES (1,"Client - 1");
INSERT INTO OPZR.ACCOUNT(OFFERING_ID, ACCOUNT_NAME) VALUES (1,"Client - 2");
INSERT INTO OPZR.ACCOUNT(OFFERING_ID, ACCOUNT_NAME) VALUES (1,"Client - 3");

INSERT INTO OPZR.PROJECT(ACCOUNT_ID, PROJECT_NAME) VALUES (2,"Team - 1");
INSERT INTO OPZR.PROJECT(ACCOUNT_ID, PROJECT_NAME) VALUES (2,"Team - 2");
INSERT INTO OPZR.PROJECT(ACCOUNT_ID, PROJECT_NAME) VALUES (3,"Team - 1");

INSERT INTO OPZR.CATEGORY(CATEGORY_NAME) VALUES ("Process Automation");
INSERT INTO OPZR.CATEGORY(CATEGORY_NAME) VALUES ("Elimination");
INSERT INTO OPZR.CATEGORY(CATEGORY_NAME) VALUES ("Proactive Automation");
INSERT INTO OPZR.CATEGORY(CATEGORY_NAME) VALUES ("Predictive Automation");

INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Incident Creation");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Categorization/Prioritization");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Incident Assigned");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Incident Acknowledged");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Incident Resolution");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Analysis and Dianosis");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Incident Closure");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Post Incident Review");

INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (2,"Incident Classification");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (2,"Known Issues - Left Shift");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (2,"Permanant Fix - Recurring Issues");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (2,"Self Help Solutions");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (2,"User Trainings");

INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (3,"Application Monitoring");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (3,"Service Monitoring");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (3,"Log Monitoring");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (3,"Event Monitoring");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (3,"Synthetic Monitoring");

INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (4,"Data Analytics");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (4,"Event Prediction");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (4,"Self Healing");

INSERT INTO OPZR.LEVER_FLOW(LEVER_ID,LEVER_FLOW_NAME) VALUES (1,"Check for Assignee Group");
INSERT INTO OPZR.LEVER_FLOW(LEVER_ID,LEVER_FLOW_NAME) VALUES (1,"Check for priority and severity of the incident");
INSERT INTO OPZR.LEVER_FLOW(LEVER_ID,LEVER_FLOW_NAME) VALUES (1,"Check for all incident details");
INSERT INTO OPZR.LEVER_FLOW(LEVER_ID,LEVER_FLOW_NAME) VALUES (1,"Create Incident");

INSERT INTO OPZR.FISCAL_YEAR(FISCAL_YEAR_DESC) VALUES ("2021");
INSERT INTO OPZR.FISCAL_YEAR(FISCAL_YEAR_DESC) VALUES ("2022");
INSERT INTO OPZR.FISCAL_YEAR(FISCAL_YEAR_DESC) VALUES ("2023");
INSERT INTO OPZR.FISCAL_YEAR(FISCAL_YEAR_DESC) VALUES ("2024");
INSERT INTO OPZR.FISCAL_YEAR(FISCAL_YEAR_DESC) VALUES ("2025");

INSERT INTO OPZR.FISCAL_QUARTER(FISCAL_YEAR_ID,FISCAL_QUARTER_DESC,START_DATE,END_DATE) VALUES (4,"Q1","2023-01-01","2023-03-31");
INSERT INTO OPZR.FISCAL_QUARTER(FISCAL_YEAR_ID,FISCAL_QUARTER_DESC,START_DATE,END_DATE) VALUES (4,"Q1","2023-04-01","2023-06-30");
INSERT INTO OPZR.FISCAL_QUARTER(FISCAL_YEAR_ID,FISCAL_QUARTER_DESC,START_DATE,END_DATE) VALUES (4,"Q1","2023-07-01","2023-09-30");
INSERT INTO OPZR.FISCAL_QUARTER(FISCAL_YEAR_ID,FISCAL_QUARTER_DESC,START_DATE,END_DATE) VALUES (4,"Q1","2023-10-01","2023-12-31");
