CREATE TABLE OPZR.OFFERING_PORTFOLIO(
	OFFERING_PORTFOLIO_ID INT PRIMARY KEY AUTO_INCREMENT,
	OFFERING_PORTFOLIO_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.OFFERING(
	OFFERING_ID INT PRIMARY KEY AUTO_INCREMENT,
	OFFERING_PORTFOLIO_ID INT NOT NULL,
	OFFERING_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	FOREIGN KEY (OFFERING_PORTFOLIO_ID) REFERENCES OFFERING_PORTFOLIO(OFFERING_PORTFOLIO_ID),
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.ACCOUNT(
	ACCOUNT_ID INT PRIMARY KEY AUTO_INCREMENT,
	OFFERING_ID INT NOT NULL,
	ACCOUNT_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	FOREIGN KEY (OFFERING_ID) REFERENCES OFFERING (OFFERING_ID),
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.PROJECT_SCOPE(
                  PROJECT_SCOPE_ID INT PRIMARY KEY AUTO_INCREMENT,
                  PROJECT_SCOPE_DESC VARCHAR(100),
                  CREATED_BY VARCHAR(50),
                  UPDATED_BY VARCHAR(50),
                  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.PROJECT(
    PROJECT_ID INT PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT_ID INT NOT NULL,
    PROJECT_NAME VARCHAR(50) NOT NULL,
    SCOPE_OF_WORK VARCHAR(50) NOT NULL,
    TEAM_SIZE INT NOT NULL,
    ONSHORE_SIZE INT NOT NULL,
    OFFSHORE_SIZE INT NOT NULL,
    ENGAGEMENT_TYPE VARCHAR(50) NOT NULL,
    OPERATING_MODEL VARCHAR(50) NOT NULL,
    IS_ACTIVE VARCHAR(2) NOT NULL DEFAULT 'Y',
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID),
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE OPZR.PROJECT_PLAN_AND_ACTUAL(
                  PROJECT_PLAN_AND_ACTUAL_ID INT PRIMARY KEY AUTO_INCREMENT,
                  PROJECT_ID INT NOT NULL,
                  PROJECT_SCOPE_ID INT NOT NULL,
                  YEAR VARCHAR(100),
                  PLANNED_FTE INT,
                  ACTUAL_FTE INT,
                  DISTRIBUTION_PERCENT DECIMAL(8,2),
                  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
                  FOREIGN KEY (PROJECT_SCOPE_ID) REFERENCES PROJECT_SCOPE(PROJECT_SCOPE_ID),
                  CREATED_BY VARCHAR(50),
                  UPDATED_BY VARCHAR(50),
                  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE OPZR.CATEGORY(
	CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	DISPLAY_ORDER INT NOT NULL,
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.LEVER(
	LEVER_ID INT PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_ID INT NOT NULL,
	LEVER_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.LEVER_FLOW(
	LEVER_FLOW_ID INT PRIMARY KEY AUTO_INCREMENT,
	LEVER_ID INT NOT NULL,
	LEVER_FLOW_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	FOREIGN KEY (LEVER_ID) REFERENCES LEVER(LEVER_ID),
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.FISCAL_YEAR_QUARTER(
    FISCAL_YEAR_QUARTER_ID INT PRIMARY KEY AUTO_INCREMENT,
    FISCAL_YEAR_QUARTER_DESC VARCHAR(50) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE VARCHAR(2) NOT NULL DEFAULT 'Y',
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.DATA_DETAIL(
    DATA_DETAIL_ID INT PRIMARY KEY AUTO_INCREMENT,
    FISCAL_YEAR_QUARTER_ID INT NOT NULL,
    LEVER_ID INT NOT NULL,
    PROJECT_ID INT NOT NULL,
    AVG_EFFORT_PER_INC DECIMAL(8,2),
    TOTAL_INCIDENTS DECIMAL(8,2),
    TOTAL_EFFORT DECIMAL(8,2),
    AUTOMATED_PERCENT DECIMAL(8,2),
    EFFORT_PERCENT DECIMAL(8,2),
    EFFORT_SAVED DECIMAL(8,2),
    SOL_IMPLEMENTED VARCHAR(1000)   ,
    SOL_link VARCHAR(5000)  ,
    FOREIGN KEY (FISCAL_YEAR_QUARTER_ID) REFERENCES FISCAL_YEAR_QUARTER(FISCAL_YEAR_QUARTER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
    FOREIGN KEY (LEVER_ID) REFERENCES LEVER(LEVER_ID),
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE OPZR.DATA_DETAIL MODIFY SOL_link VARCHAR(5000);

ALTER TABLE `opzr`.`category`
ADD COLUMN `DISPLAY_COLUMNS_LABELS` VARCHAR(200) NOT NULL AFTER `DISPLAY_ORDER`;

ALTER TABLE OPZR.DATA_DETAIL
ADD COLUMN PRICED_AVG_EFFORT_PER_INC DECIMAL(8,2),
ADD COLUMN PRICED_AVG_INCIDENTS_PER_QTR DECIMAL(8,2),
ADD COLUMN ACTUAL_AVG_EFFORT_PER_INC DECIMAL(8,2),
ADD COLUMN ACTUAL_AVG_INCIDENTS_PER_QTR DECIMAL(8,2),
DROP COLUMN AVG_EFFORT_PER_INC,
DROP COLUMN TOTAL_INCIDENTS,
DROP COLUMN SOL_IMPLEMENTED ,
DROP COLUMN SOL_link,
MODIFY COLUMN TOTAL_EFFORT DECIMAL(8,2),
MODIFY COLUMN AUTOMATED_PERCENT DECIMAL(8,2),
MODIFY COLUMN EFFORT_PERCENT DECIMAL(8,2),
MODIFY COLUMN EFFORT_SAVED DECIMAL(8,2);


ALTER TABLE OPZR.CATEGORY
ADD COLUMN PROJECT_SCOPE_ID INT NOT NULL AFTER CATEGORY_NAME,
ADD FOREIGN KEY (PROJECT_SCOPE_ID) REFERENCES PROJECT_SCOPE(PROJECT_SCOPE_ID);

ALTER TABLE OPZR.PROJECT
ADD COLUMN START_DATE DATE NOT NULL AFTER OFFSHORE_SIZE,
ADD COLUMN END_DATE DATE NOT NULL AFTER START_DATE;


CREATE TABLE OPZR.SOLUTION_DETAIL(
SOLUTION_ID INT PRIMARY KEY AUTO_INCREMENT,
SOLUTION_IMPLEMENTED VARCHAR(5000),
SOLUTION_LINK VARCHAR(2000),
TECHNOLOGIES_USED VARCHAR(2000),
DATA_DETAIL_ID INT NOT NULL,
FOREIGN KEY (DATA_DETAIL_ID) REFERENCES DATA_DETAIL(DATA_DETAIL_ID));

CREATE TABLE OPZR.SCOPE(
SCOPE_ID INT PRIMARY KEY AUTO_INCREMENT,
SCOPE_NAME VARCHAR(50) NOT NULL,
IS_ACTIVE BIT NOT NULL DEFAULT 0,
CREATED_BY VARCHAR(50),
UPDATED_BY VARCHAR(50),
CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

ALTER TABLE OPZR.CATEGORY
ADD COLUMN SCOPE_ID INT NOT NULL AFTER CATEGORY_NAME;

ALTER TABLE OPZR.CATEGORY
ADD FOREIGN KEY (SCOPE_ID) REFERENCES SCOPE(SCOPE_ID);

ALTER TABLE OPZR.CATEGORY
ADD COLUMN SCOPE_ID INT NOT NULL AFTER CATEGORY_NAME;

ALTER TABLE OPZR.SCOPE
ADD COLUMN 	DISPLAY_ORDER INT NOT NULL;