
INSERT INTO OPZR.OFFERING_PORTFOLIO(OFFERING_PORTFOLIO_NAME) VALUES ("Core Business Operations");

INSERT INTO OPZR.OFFERING(OFFERING_PORTFOLIO_ID, OFFERING_NAME) VALUES (1,"Core Technology Operations");
INSERT INTO OPZR.OFFERING(OFFERING_PORTFOLIO_ID, OFFERING_NAME) VALUES (1,"Cloud Engineering");
INSERT INTO OPZR.OFFERING(OFFERING_PORTFOLIO_ID, OFFERING_NAME) VALUES (1,"Application Mordernization and Innovation");

INSERT INTO OPZR.ACCOUNT(OFFERING_ID, ACCOUNT_NAME) VALUES (1,"Client - 1");
INSERT INTO OPZR.ACCOUNT(OFFERING_ID, ACCOUNT_NAME) VALUES (1,"Client - 2");
INSERT INTO OPZR.ACCOUNT(OFFERING_ID, ACCOUNT_NAME) VALUES (1,"Client - 3");

INSERT INTO OPZR.PROJECT (ACCOUNT_ID, PROJECT_NAME, SCOPE_OF_WORK, TEAM_SIZE, ONSHORE_SIZE, OFFSHORE_SIZE, ENGAGEMENT_TYPE, OPERATING_MODEL, CREATED_BY, UPDATED_BY)
VALUES (2, 'Project ABC', 'Software Development', 10, 5, 5, 'Fixed Price', 'Onsite-Offshore', 'John Doe', 'Jane Smith');

INSERT INTO OPZR.CATEGORY(CATEGORY_NAME,DISPLAY_ORDER) VALUES ("Process Automation",1);
INSERT INTO OPZR.CATEGORY(CATEGORY_NAME,DISPLAY_ORDER) VALUES ("Elimination",2);
INSERT INTO OPZR.CATEGORY(CATEGORY_NAME,DISPLAY_ORDER) VALUES ("Proactive Automation",3);
INSERT INTO OPZR.CATEGORY(CATEGORY_NAME,DISPLAY_ORDER) VALUES ("Predictive Automation",4);

INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Incident Creation");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Categorization/Prioritization");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Incident Assigned");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Incident Acknowledged");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Incident Resolution");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Analysis and Dianosis");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Incident Closure");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (1,"Post Incident Review");

INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (2,"Incident Classification");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (2,"Known Issues - Left Shift");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (2,"Permanant Fix - Recurring Issues");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (2,"Self Help Solutions");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (2,"User Trainings");

INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (3,"Application Monitoring");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (3,"Service Monitoring");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (3,"Log Monitoring");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (3,"Event Monitoring");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (3,"Synthetic Monitoring");

INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (4,"Data Analytics");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (4,"Event Prediction");
INSERT INTO OPZR.LEVER(CATEGORY_ID,LEVER_NAME) VALUES (4,"Self Healing");

INSERT INTO OPZR.LEVER_FLOW(LEVER_ID,LEVER_FLOW_NAME) VALUES (1,"Check for Assignee Group");
INSERT INTO OPZR.LEVER_FLOW(LEVER_ID,LEVER_FLOW_NAME) VALUES (1,"Check for priority and severity of the incident");
INSERT INTO OPZR.LEVER_FLOW(LEVER_ID,LEVER_FLOW_NAME) VALUES (1,"Check for all incident details");
INSERT INTO OPZR.LEVER_FLOW(LEVER_ID,LEVER_FLOW_NAME) VALUES (1,"Create Incident");

INSERT INTO OPZR.FISCAL_YEAR_QUARTER(FISCAL_YEAR_QUARTER_DESC) VALUES ("FY2024-Q1");

INSERT INTO OPZR.DATA_DETAIL(FISCAL_YEAR_QUARTER_ID,LEVER_ID,PROJECT_ID) VALUES (1,1,1);
