CREATE TABLE OPZR.OFFERING_PORTFOLIO(
	OFFERING_PORTFOLIO_ID INT PRIMARY KEY AUTO_INCREMENT,
	OFFERING_PORTFOLIO_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.OFFERING(
	OFFERING_ID INT PRIMARY KEY AUTO_INCREMENT,
	OFFERING_PORTFOLIO_ID INT NOT NULL,
	OFFERING_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	FOREIGN KEY (OFFERING_PORTFOLIO_ID) REFERENCES OFFERING_PORTFOLIO(OFFERING_PORTFOLIO_ID),
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.ACCOUNT(
	ACCOUNT_ID INT PRIMARY KEY AUTO_INCREMENT,
	OFFERING_ID INT NOT NULL,
	ACCOUNT_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	FOREIGN KEY (OFFERING_ID) REFERENCES OFFERING (OFFERING_ID),
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.PROJECT(
    PROJECT_ID INT PRIMARY KEY AUTO_INCREMENT,
    ACCOUNT_ID INT NOT NULL,
    PROJECT_NAME VARCHAR(50) NOT NULL,
    SCOPE_OF_WORK VARCHAR(50) NOT NULL,
    TEAM_SIZE INT NOT NULL,
    ONSHORE_SIZE INT NOT NULL,
    OFFSHORE_SIZE INT NOT NULL,
    ENGAGEMENT_TYPE VARCHAR(50) NOT NULL,
    OPERATING_MODEL VARCHAR(50) NOT NULL,
    IS_ACTIVE VARCHAR(2) NOT NULL DEFAULT 'Y',
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ACCOUNT_ID),
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.CATEGORY(
	CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.LEVER(
	LEVER_ID INT PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_ID INT NOT NULL,
	LEVER_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.LEVER_FLOW(
	LEVER_FLOW_ID INT PRIMARY KEY AUTO_INCREMENT,
	LEVER_ID INT NOT NULL,
	LEVER_FLOW_NAME VARCHAR(50) NOT NULL,
	IS_ACTIVE BIT NOT NULL DEFAULT 0,
	FOREIGN KEY (LEVER_ID) REFERENCES LEVER(LEVER_ID),
	CREATED_BY VARCHAR(50),
	UPDATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.FISCAL_YEAR_QUARTER(
    FISCAL_YEAR_QUARTER_ID INT PRIMARY KEY AUTO_INCREMENT,
    FISCAL_YEAR_QUARTER_DESC VARCHAR(50) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    IS_ACTIVE VARCHAR(2) NOT NULL DEFAULT 'Y',
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE OPZR.DATA_DETAIL(
    DATA_DETAIL_ID INT PRIMARY KEY AUTO_INCREMENT,
    FISCAL_YEAR_QUARTER_ID INT NOT NULL,
    LEVER_ID INT NOT NULL,
    PROJECT_ID INT NOT NULL,
    AUTOMATED_PERCENT DECIMAL(3,2),
    EFFORT_PERCENT DECIMAL(3,2),
    EFFORT_SAVED DECIMAL(3,2),    
    FOREIGN KEY (FISCAL_YEAR_QUARTER_ID) REFERENCES FISCAL_YEAR_QUARTER(FISCAL_YEAR_QUARTER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID),
    FOREIGN KEY (LEVER_ID) REFERENCES LEVER(LEVER_ID),
    CREATED_BY VARCHAR(50),
    UPDATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);