INSERT INTO OPZR.OFFERING_PORTFOLIO (OFFERING_PORTFOLIO_NAME, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES ('Portfolio 1', 1, 'User1', 'User2');

INSERT INTO OPZR.OFFERING (OFFERING_PORTFOLIO_ID, OFFERING_NAME, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES (1, 'Offering 1', 1, 'User3', 'User4');

INSERT INTO OPZR.ACCOUNT (OFFERING_ID, ACCOUNT_NAME, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES (1, 'Account 1', 1, 'User5', 'User6');

INSERT INTO OPZR.PROJECT_SCOPE (PROJECT_SCOPE_DESC, CREATED_BY, UPDATED_BY)
VALUES ('Scope 1', 'User7', 'User8');

INSERT INTO OPZR.PROJECT (ACCOUNT_ID, PROJECT_NAME, SCOPE_OF_WORK, TEAM_SIZE, ONSHORE_SIZE, OFFSHORE_SIZE, ENGAGEMENT_TYPE, OPERATING_MODEL, START_DATE, END_DATE, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES (1, 'Project 1', 'Scope 1', 10, 5, 5, 'Engagement 1', 'Model 1', '2023-01-01', '2023-12-31', 'Y', 'User13', 'User14');

INSERT INTO OPZR.PROJECT_PLAN_AND_ACTUAL (PROJECT_ID, PROJECT_SCOPE_ID, YEAR, PLANNED_FTE, ACTUAL_FTE, DISTRIBUTION_PERCENT, CREATED_BY, UPDATED_BY)
VALUES (1, 1, '2023', 10, 8, 80.00, 'User11', 'User12');

INSERT INTO OPZR.CATEGORY (CATEGORY_NAME,PROJECT_SCOPE_ID, IS_ACTIVE, DISPLAY_ORDER, DISPLAY_COLUMNS_LABELS, CREATED_BY, UPDATED_BY)
VALUES ('Category 1', 1,1, 1, 'Label 1', 'User13', 'User14');

INSERT INTO OPZR.LEVER (CATEGORY_ID, LEVER_NAME, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES (1, 'Lever 1', 1, 'User15', 'User16');

INSERT INTO OPZR.LEVER_FLOW (LEVER_ID, LEVER_FLOW_NAME, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES (1, 'Lever Flow 1', 1, 'User17', 'User18');

INSERT INTO OPZR.FISCAL_YEAR_QUARTER (FISCAL_YEAR_QUARTER_DESC, START_DATE, END_DATE, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES ('Q1 2023', '2023-01-01', '2023-03-31', 'Y', 'User19', 'User20');

INSERT INTO OPZR.DATA_DETAIL (FISCAL_YEAR_QUARTER_ID, LEVER_ID, PROJECT_ID, PRICED_AVG_EFFORT_PER_INC, PRICED_AVG_INCIDENTS_PER_QTR, ACTUAL_AVG_EFFORT_PER_INC, ACTUAL_AVG_INCIDENTS_PER_QTR, CREATED_BY, UPDATED_BY)
VALUES (1, 1, 1, 20.00, 5.00, 18.00, 4.00, 'User21', 'User22');

INSERT INTO OPZR.SOLUTION_DETAIL (SOLUTION_IMPLEMENTED, TECHNOLOGIES_USED,SOLUTION_LINK, DATA_DETAIL_ID)
VALUES ('Solution Implemented 1', 'Technology 1, Technology 2', 'www.solutionlink.com',1);

INSERT INTO OPZR.Scope (scope_name,SCOPE_ID, IS_ACTIVE, CREATED_BY, UPDATED_BY)
VALUES ('scope 1', 1,1, 'User13', 'User14');

